version: '3.7'

services:
  cqrs_ddd_php_app:
    container_name: cqrs_ddd_php_app
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: cqrs_ddd_php_app
    restart: always
    ports:
      - '8001:80'
    networks:
      - cqrs_ddd_php_network
    volumes:
      - ./:/var/www/html/

  cqrs_ddd_php_postgres:
    container_name: cqrs_ddd_php_postgres
    image: postgres:11.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always
    volumes:
      - cqrs_ddd_php_postgres_volume:/var/lib/postgresql
    networks:
      - cqrs_ddd_php_network

  cqrs_ddd_php_eventstore:
    container_name: cqrs_ddd_php_eventstore
    image: eventstore/eventstore
    restart: always
    ports:
       - '1113:1113'
       - '2113:2113'
    networks:
      - cqrs_ddd_php_network

  cqrs_ddd_php_rabbitmq:
    container_name: cqrs_ddd_php_rabbitmq
    image: rabbitmq:3.7.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    restart: always
    ports:
       - '5672:5672'
       - '15672:15672'
    networks:
      - cqrs_ddd_php_network

networks:
  cqrs_ddd_php_network:
    name: cqrs_ddd_php_network

volumes:
  cqrs_ddd_php_postgres_volume: