Sample\Domain\Entity\Order:
  type: entity
  repositoryClass: Sample\Domain\Repository\OrderRepository
  table: Order
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    userId:
      type: integer
      column: user_id
      nullable: false
    amount:
      type: float
      column: amount
      nullable: false
    createdAt:
      type: datetime
      column: created_at
      nullable: false