Sample\Domain\Entity\Order:
  type: entity
  repositoryClass: Sample\Domain\Repository\OrderRepository
  table: order_
  id:
    id:
      type: string
      generator:
        strategy: none
  fields:
    amount:
      type: float
      column: amount
      nullable: false
    status:
      type: string
      column: status
      nullable: false
    createdAt:
      type: datetime
      column: created_at
      nullable: false
  manyToOne:
    user:
      targetEntity: Sample\Domain\Entity\User
      joinColumn:
        name: user_id
        referencedColumnName: id
    product:
      targetEntity: Sample\Domain\Entity\Product
      joinColumn:
        name: product_id
        referencedColumnName: id
