Sample\Domain\Entity\User:
  type: entity
  repositoryClass: Sample\Domain\Repository\UserRepository
  table: User_
  id:
    id:
      type: string
      generator:
        strategy: NONE
  fields:
    fullName:
      type: string
      column: full_name
      nullable: false
    birthday:
      type: datetime
      column: birthday
      nullable: false
    username:
      type: string
      column: username
      nullable: false
    password:
      type: string
      column: password
      nullable: false
    createdAt:
      type: datetime
      column: created_at
      nullable: false
