services:
  _defaults:
    autoconfigure: true

  # Subscriber

  codely.video.notification.subscriber.create_notification_on_video_created:
    class: CodelyTv\Context\Video\Module\Notification\Application\Create\CreateNotificationOnVideoCreated
    arguments:
      - '@codely.video.notification.notification_creator'

  codely.video.notification.subscriber.send_notification_on_notification_created:
    class: CodelyTv\Context\Video\Module\Notification\Application\Send\SendStaffNotificationOnNotificationCreated
    arguments:
      - '@codely.video.notification.notification_sender'


  # Services

  codely.video.notification.notification_creator:
    class: CodelyTv\Context\Video\Module\Notification\Application\Create\NotificationCreator
    arguments:
     - '@codely.infrastructure.uuid_generator'
     - '@codely.video.domain_event_publisher'

  codely.video.notification.notification_sender:
    class: CodelyTv\Context\Video\Module\Notification\Application\Send\NotificationSender
    arguments:
     - '@codely.video.notification.notifier'
