@startuml

actor User
control Query #99FF99
control Command #99FF99
database Persistence
collections UserInterface

User -down-|> UserInterface: Data
UserInterface -down-|> Command: Data
UserInterface -down-|> Query: Filter
Query -up-|> UserInterface: Data

Command -down-|> Persistence: Data
Query -down-|> Persistence: Filter
Persistence -up-|> Query: Data

@enduml