services:

  codely.video.async_command_bus:
    alias: codely.infrastructure.async_command_bus

  codely.video.command_bus:
    class: CodelyTv\Infrastructure\Bus\Command\SymfonySyncCommandBus
    arguments: [!tagged codely.video.command]
    lazy: true

  codely.video.query_bus:
    class: CodelyTv\Infrastructure\Bus\Query\SymfonySyncQueryBus
    arguments: [!tagged codely.video.query]
    lazy: true

  codely.video.event_bus:
    class: CodelyTv\Infrastructure\Bus\Event\SymfonySyncEventBus
    arguments: [!tagged codely.video.subscriber]
    lazy: true
    public: true

  codely.video.domain_event_publisher:
    class: CodelyTv\Infrastructure\Bus\Event\SymfonySyncDomainEventPublisher
    lazy: true
    public: true
