imports:

  - { resource: infrastructure_domain_event.yml }
  - { resource: infrastructure_shared.yml }


services:
  codely.infrastructure.async_command_bus:
    class: CodelyTv\Infrastructure\Bus\Command\CommandBusAsync
    arguments:
        $pendingRequestsFilePath: '%async_command_bus_pending_requests_file_path%'
    lazy: true

  codely.infrastructure.database_connections:
    class: CodelyTv\Infrastructure\Doctrine\DatabaseConnections

  codely.infrastructure.uuid_generator:
    class: CodelyTv\Infrastructure\Uuid\UuidGenerator
